CREATE TABLE IF NOT EXISTS `battery_charging` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `invoice_no` VARCHAR(50) NOT NULL,
  `bill_date` DATE NULL,
  `customer_name` VARCHAR(255) NULL,
  `address` TEXT NULL,
  `deposit_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `loan_hire_per_day` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `ready_date` DATE NULL,
  `make` VARCHAR(100) NULL,
  `voltage` VARCHAR(50) NULL,
  `battery_no` VARCHAR(100) NULL,
  `loan_battery` VARCHAR(100) NULL,
  `acid` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `repairs` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `charging` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `company_id` INT(11) NULL,
  `created_by` INT(11) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_no` (`invoice_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
